from .pg_db import db
from .phone_data import PHONE_BRANDS, PHONE_MODELS, PHONE_MEMORY_OPTIONS, PHONE_CONDITIONS, UZBEKISTAN_REGIONS

__all__ = ["db", "PHONE_BRANDS", "PHONE_MODELS", "PHONE_MEMORY_OPTIONS", "PHONE_CONDITIONS", "UZBEKISTAN_REGIONS"]
